<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class BulkUpdate extends Model
{
    /** @use HasFactory<\Database\Factories\BulkUpdateFactory> */
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'user_id',
        'pass_template_id',
        'field_key',
        'field_value',
        'filters',
        'status',
        'total_count',
        'processed_count',
        'failed_count',
        'started_at',
        'completed_at',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'filters' => 'array',
            'started_at' => 'datetime',
            'completed_at' => 'datetime',
        ];
    }

    /**
     * Get the user associated with this bulk update.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the pass template associated with this bulk update.
     */
    public function passTemplate(): BelongsTo
    {
        return $this->belongsTo(PassTemplate::class);
    }

    /**
     * Get pass updates generated by this bulk update.
     */
    public function passUpdates(): HasMany
    {
        return $this->hasMany(PassUpdate::class);
    }

    /**
     * Scope a query to bulk updates currently in progress.
     */
    public function scopeInProgress(Builder $query): Builder
    {
        return $query->whereIn('status', ['pending', 'processing']);
    }
}
